name: zeetionary
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^4.11.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.11.1
  firebase_core: ^2.15.1
  firebase_storage: ^11.3.1
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.5
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  flutter_tts: ^3.8.3
  fpdart: ^1.1.0
  go_router: ^12.0.0
  google_sign_in: ^6.1.5
  provider: ^6.0.5
  routemaster: ^1.0.0
  shared_preferences: ^2.2.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google.png
    - assets/images/kurd_one.png
    - assets/images/uk_one.png
    - assets/images/video_one.png
    - assets/images/zee_splash.png
    - assets/images/zeetionary_one.png
    - assets/images/zeetionary_three.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
