export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dismember.dart' show EnglishEntrydismember;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dismiss.dart' show EnglishEntrydismiss;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dismissal.dart' show EnglishEntrydismissal;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disobedient.dart' show EnglishEntrydisobedient;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disobedience.dart' show EnglishEntrydisobedience;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disobediently.dart' show EnglishEntrydisobediently;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disobey.dart' show EnglishEntrydisobey;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorder.dart' show EnglishEntrydisorder;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorderly.dart' show EnglishEntrydisorderly;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorganized.dart' show EnglishEntrydisorganized;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorganization.dart' show EnglishEntrydisorganization;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorientate.dart' show EnglishEntrydisorientate;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disorientation.dart' show EnglishEntrydisorientation;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disown.dart' show EnglishEntrydisown;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disparaging.dart' show EnglishEntrydisparaging;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disparate.dart' show EnglishEntrydisparate;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disparity.dart' show EnglishEntrydisparity;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispassionate.dart' show EnglishEntrydispassionate;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispassionately.dart' show EnglishEntrydispassionately;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispatch.dart' show EnglishEntrydispatch;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispel.dart' show EnglishEntrydispel;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispense.dart' show EnglishEntrydispense;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispensary.dart' show EnglishEntrydispensary;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispensation.dart' show EnglishEntrydispensation;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_disperse.dart' show EnglishEntrydisperse;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispersal.dart' show EnglishEntrydispersal;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_dispirited.dart' show EnglishEntrydispirited;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_displace.dart' show EnglishEntrydisplace;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_displacement.dart' show EnglishEntrydisplacement;
export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_display.dart' show EnglishEntrydisplay;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;
// export 'package:zeetionary/dictionary/english_dictionary/alphabet/letter_d/en_entry_DOPSUM.dart' show EnglishEntry;