import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:zeetionary/constants.dart';

class HistoryScreen extends StatelessWidget {
  const HistoryScreen({super.key});

  Future<void> clearHistory() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.remove('history');
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Scaffold(
        appBar: const ZeetionaryAppbar(),
        body: FutureBuilder<List<String>>(
          future: loadHistory(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const CircularProgressIndicator();
            } else if (snapshot.hasData) {
              final history = snapshot.data;
              return ListView.builder(
                itemCount: history?.length,
                itemBuilder: (context, index) {
                  final word = history![index];
                  return ListTile(
                    trailing: const Icon(Icons.arrow_forward),
                    title: Text(word),
                    onTap: () {
                      // Navigate to the corresponding screen based on the tapped word
                      navigateToScreen(context, word);
                    },
                  );
                },
              );
            } else {
              return const Text('No history found.');
            }
          },
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            clearHistory();
            ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
              content: Directionality(
                textDirection: TextDirection.rtl,
                child: Text('پاککرایەوە'),
              ),
            ));
          },
          child: const Icon(Icons.delete),
        ),
      ),
    );
  }

  Future<List<String>> loadHistory() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    List<String> history = prefs.getStringList('history') ?? [];

    // Reverse the order of the history list
    return history.reversed.toList();
  }

  void navigateToScreen(BuildContext context, String word) {
    final screenRoutes = {
      "a": '/english-a',
      "aback": '/english-aback',
      "abacus": '/english-abacus',
      "abandon": '/english-abandon',
      'abandoned': '/english-abandoned',
      'abandonment': '/english-abandonment',
      'abashed': '/english-abashed',
      'abate': '/english-abate',
      'abatement': '/english-abatement',
      'abattoir': '/english-abattoir',
      'abbess': '/english-abbess',
      'abbey': '/english-abbey',
      'abbot': '/english-abbot',
      "abbreviate": '/english-abbreviate',
      "abbreviation": '/english-abbreviation',
      "abdicate": '/english-abdicate',
      "abdication": '/english-abdication',
      "abdomen": '/english-abdomen',
      "abdominal": '/english-abdominal',
      "abduct": '/english-abduct',
      "abduction": '/english-abduction',
      "aberration": '/english-aberration',
      "abet": '/english-abet',
      "abhor": '/english-abhor',
      "abhorrence": '/english-abhorrence',
      "abhorrent": '/english-abhorrent',
      "abide": '/english-abide',
      "abiding": '/english-abiding',
      "ability": '/english-ability',
      "abject": '/english-abject',
      "abjectly": '/english-abjectly',
      "ablaze": '/english-ablaze',
      "able": '/english-able',
      "able-bodied": '/english-able-bodied',
      "abnormal": '/english-abnormal',
      "abnormality": '/english-abnormality',
      "abnormally": '/english-abnormally',
      "aboard": '/english-aboard',
      "abode": '/english-abode',
      "abolish": '/english-abolish',
      "abolition": '/english-abolition',
      "abominable": '/english-abominable',
      "abominably": '/english-abominably',
      "aboriginal": '/english-aboriginal',
      "aborigine": '/english-aborigine',
      "abort": '/english-abort',
      "abortion": '/english-abortion',
      "abortive": '/english-abortive',
      "abound": '/english-abound',
      "abound in": '/english-abound-in',
      "abound with": '/english-abound-with',
      "about": '/english-about',
      "about turn": '/english-about-turn',
      "above": '/english-above',
      "the above": '/english-the-above',
      "above all": '/english-above-all',
      "above/below the fold": '/english-above-below-the-fold',
      "above/beyond suspicion": '/english-above-beyond-suspicion',
      "above yourself": '/english-above-yourself',
      "abrasion": '/english-abrasion',
      "abrasive": '/english-abrasive',
      "abreast": '/english-abreast',
      "abridge": '/english-abridge',
      "abridgement": '/english-abridgement',
      "abroad": '/english-abroad',
      "abrupt": '/english-abrupt',
      "abruptly": '/english-abruptly',
      "abruptness": '/english-abruptness',
      "abscess": '/english-abscess',
      "abscond": '/english-abscond',
      "abseil": '/english-abseil',
      "absence": '/english-absence',
      "absent": '/english-absent',
      "absentee": '/english-absentee',
      "absent-minded": '/english-absent-minded',
      "absolute": '/english-absolute',
      "absolutely": '/english-absolutely',
      "absolute majority": '/english-absolute-majority',
      "absolute zero": '/english-absolute-zero',
      "absolve": '/english-absolve',
      "absorb": '/english-absorb',
      "absorbent": '/english-absorbent',
      "absorption": '/english-absorption',
      "abstain": '/english-abstain',
      "abstemious": '/english-abstemious',
      "abstention": '/english-abstention',
      "abstinence": '/english-abstinence',
      "abstract": '/english-abstract',
      "absurd": '/english-absurd',
      "absurdity": '/english-absurdity',
      "absurdly": '/english-absurdly',
      "abundance": '/english-abundance',
      "abundant": '/english-abundant',
      "abundantly": '/english-abundantly',
      "abuse": '/english-abuse',
      "abusive": '/english-abusive',
      "abysmal": '/english-abysmal',
      "abysmally": '/english-abysmally',
      "abyss": '/english-abyss',
      "academic": '/english-academic',
      "academically": '/english-academically',
      "academy": '/english-academy',
      "accede": '/english-accede',
      "accelerate": '/english-accelerate',
      "acceleration": '/english-acceleration',
      "accelerator": '/english-accelerator',
      "accent": '/english-accent',
      "accentuate": '/english-accentuate',
      "accept": '/english-accept',
      "acceptable": '/english-acceptable',
      "acceptance": '/english-acceptance',
      "access": '/english-access',
      "accessible": '/english-accessible',
      "accession": '/english-accession',
      "accessory": '/english-accessory',
      "accident": '/english-accident',
      "accidental": '/english-accidental',
      "accidentally": '/english-accidentally',
      "acclaim": '/english-acclaim',
      "acclimatize": '/english-acclimatize',
      "accolade": '/english-accolade',
      "accommodate": '/english-accommodate',
      "accommodating": '/english-accommodating',
      "accommodation": '/english-accommodation',
      "accompaniment": '/english-accompaniment',
      "accompanist": '/english-accompanist',
      "accompany": '/english-accompany',
      "accomplice": '/english-accomplice',
      "accomplish": '/english-accomplish',
      "accomplished": '/english-accomplished',
      "accomplishment": '/english-accomplishment',
      "accord": '/english-accord',
      "accordingly": '/english-accordingly',
      "according to": '/english-according-to',
      "accordion": '/english-accordion',
      "accost": '/english-accost',
      "account": '/english-account',
      "account for": '/english-account-for',
      "accountable": '/english-accountable',
      "accountancy": '/english-accountancy',
      "accountant": '/english-accountant',
      "accredited": '/english-accredited',
      "accreditation": '/english-accreditation',
      "accrue": '/english-accrue',
      "accumulate": '/english-accumulate',
      "accumulation": '/english-accumulation',
      "accuracy": '/english-accuracy',
      "accurate": '/english-accurate',
      "accurately": '/english-accurately',
      "accusation": '/english-accusation',
      "accuse": '/english-accuse',
      "the accused": '/english-the-accused',
      "accuser": '/english-accuser',
      "accustom to": '/english-accustom-to',
      "accustomed": '/english-accustomed',
      "ace": '/english-ace',
      "ache": '/english-ache',
      "achieve": '/english-achieve',
      "achievement": '/english-achievement',
      "Achilles' heel": '/english-achilles-heel',
      "acid rain": '/english-acid-rain',
      "acid test": '/english-acid-test',
      "acknowledge": '/english-acknowledge',
      "acknowledgement": '/english-acknowledgement',
      "acne": '/english-acne',
      "acorn": '/english-acorn',
      "acoustic": '/english-acoustic',
      "acoustics": '/english-acoustics',
      "acquaint": '/english-acquaint',
      "acquaintance": '/english-acquaintance',
      "acquainted": '/english-acquainted',
      "acquiesce": '/english-acquiesce',
      "acquiescence": '/english-acquiescence',
      "acquire": '/english-acquire',
      "acquisition": '/english-acquisition',
      "acquisitive": '/english-acquisitive',
      "acquit": '/english-acquit',
      "acquittal": '/english-acquittal',
      "acre": '/english-acre',
      "acreage": '/english-acreage',
      "acrid": '/english-acrid',
      "acrimonious": '/english-acrimonious',
      "acrimony": '/english-acrimony',
      "acrobat": '/english-acrobat',
      "acrobatic": '/english-acrobatic',
      "acrobatics": '/english-acrobatics',
      "acronym": '/english-acronym',
      "across": '/english-across',
      "acrylic": '/english-acrylic',
      "act": '/english-act',
      "action": '/english-action',
      "activate": '/english-activate',
      "active": '/english-active',
      "actively": '/english-actively',
      "activist": '/english-activist',
      "activity": '/english-activity',
      "actor": '/english-actor',
      "actress": '/english-actress',
      "actual": '/english-actual',
      "actually": '/english-actually',
      "acumen": '/english-acumen',
      "acupuncture": '/english-acupuncture',
      "acute": '/english-acute',
      "acute accent": '/english-acute accent',
      "acute angle": '/english-acute-angle',
      "acutely": '/english-acutely',
      "acuteness": '/english-acuteness',
      "ad": '/english-ad',
      "adamant": '/english-adamant',
      "Adam's apple": '/english-adams-apple',
      "adapt": '/english-adapt',
      "adaptable": '/english-adaptable',
      "adaptation": '/english-adaptation',
      "adaptor": '/english-adaptor',
      "add": '/english-add',
      "adder": '/english-adder',
      "addict": '/english-addict',
      "addicted": '/english-addicted',
      "addiction": '/english-addiction',
      "addictive": '/english-addictive',
      "addition": '/english-addition',
      "additional": '/english-additional',
      "additionally": '/english-additionally',
      "additive": '/english-additive',
      "address": '/english-address',
      "adequate": '/english-adequate',
      "adequately": '/english-adequately',
      "adhere": '/english-adhere',
      "adhere to": '/english-adhere-to',
      "adherence": '/english-adherence',
      "adherent": '/english-adherent',
      "adhesion": '/english-adhesion',
      "adhesive": '/english-adhesive',
      "ad hoc": '/english-ad-hoc',
      "adjacent": '/english-adjacent',
      "adjectival": '/english-adjectival',
      "adjective": '/english-adjective',
      "adjoin": '/english-adjoin',
      "adjourn": '/english-adjourn',
      "adjournment": '/english-adjournment',
      "adjudicate": '/english-adjudicate',
      "adjudication": '/english-adjudication',
      "adjudicator": '/english-adjudicator',
      "adjunct": '/english-adjunct',
      "adjust": '/english-adjust',
      "adjustable": '/english-adjustable',
      "adjustment": '/english-adjustment',
      "ad lib": '/english-ad-lib',
      "administer": '/english-administer',
      "administration": '/english-administration',
      "administrative": '/english-administrative',
      "administrator": '/english-administrator',
      "admirable": '/english-admirable',
      "admirably": '/english-admirably',
      "admiral": '/english-admiral',
      "admiration": '/english-admiration',
      "admire": '/english-admire',
      "admirer": '/english-admirer',
      "admiring": '/english-admiring',
      "admissible": '/english-admissible',
      "admission": '/english-admission',
      "admit": '/english-admit',
      "admittance": '/english-admittance',
      "admittedly": '/english-admittedly',
      "admonish": '/english-admonish',
      "ad nauseam": '/english-ad-nauseam',
      "adolescence": '/english-adolescence',
      "adolescent": '/english-adolescent',
      "adopt": '/english-adopt',
      "adoption": '/english-adoption',
      "adoptive": '/english-adoptive',
      "adorable": '/english-adorable',
      "adoration": '/english-adoration',
      "adore": '/english-adore',
      "adorn": '/english-adorn',
      "adornment": '/english-adornment',
      "adrenaline": '/english-adrenaline',
      "adrift": '/english-adrift',
      "adulation": '/english-adulation',
      "adulterate": '/english-adulterate',
      "adulterer": '/english-adulterer',
      "adulterous": '/english-adulterous',
      "adultery": '/english-adultery',
      "adulthood": '/english-adulthood',
      "advance": '/english-advance',
      "advanced": '/english-advanced',
      "advancement": '/english-advancement',
      "advantage": '/english-advantage',
      "advantageous": '/english-advantageous',
      "advent": '/english-advent',
      "adventure": '/english-adventure',
      "adventurer": '/english-adventurer',
      "adventurous": '/english-adventurous',
      "adverb": '/english-adverb',
      "adverbial": '/english-adverbial',
      "adversary": '/english-adversary',
      "adverse": '/english-adverse',
      "adversely": '/english-adversely',
      "adversity": '/english-adversity',
      "advert": '/english-advert',
      "advertise": '/english-advertise',
      "advertisement": '/english-advertisement',
      "advertiser": '/english-advertiser',
      "advertising": '/english-advertising',
      "advisable": '/english-advisable',
      "advise": '/english-advise',
      "adviser": '/english-adviser',
      "advisory": '/english-advisory',
      "advocate": '/english-advocate',
      "aerial": '/english-aerial',
      "aerobatics": '/english-aerobatics',
      "aerobics": '/english-aerobics',
      "aerodynamic": '/english-aerodynamic',
      "aerodynamics": '/english-aerodynamics',
      "aeronautics": '/english-aeronautics',
      "aeroplane": '/english-aeroplane',
      "aerosol": '/english-aerosol',
      "aerospace": '/english-aerospace',
      "aesthetic": '/english-aesthetic',
      "aesthetically": '/english-aesthetically',
      "affable": '/english-affable',
      "affably": '/english-affably',
      "affair": '/english-affair',
      "affect": '/english-affect',
      "affectation": '/english-affectation',
      "affected": '/english-affected',
      "affection": '/english-affection',
      "affectionate": '/english-affectionate',
      "affectionately": '/english-affectionately',
      "affidavit": '/english-affidavit',
      "affiliate": '/english-affiliate',
      "affiliation": '/english-affiliation',
      "affinity": '/english-affinity',
      "affirm": '/english-affirm',
      "affirmation": '/english-affirmation',
      "affirmative": '/english-affirmative',
      "affix": '/english-affix',
      "afflict": '/english-afflict',
      "affliction": '/english-affliction',
      "affluence": '/english-affluence',
      "affluent": '/english-affluent',
      "afford": '/english-afford',
      "affront": '/english-affront',
      "afloat": '/english-afloat',
      "afoot": '/english-afoot',
      "aforementioned": '/english-aforementioned',
      "afraid": '/english-afraid',
      "afresh": '/english-afresh',
      "after": '/english-after',
      "aftereffect": '/english-aftereffect',
      "aftermath": '/english-aftermath',
      "afternoon": '/english-afternoon',
      "afterthought": '/english-afterthought',
      "afterwards": '/english-afterwards',
      "again": '/english-again',
      "against": '/english-against',
      "age": '/english-age',
      "age group": '/english-age-group',
      "ageing": '/english-ageing',
      "ageism": '/english-ageism',
      "ageist": '/english-ageist',
      "age limit": '/english-age-limit',
      "agency": '/english-agency',
      "agenda": '/english-agenda',
      "age-old": '/english-age-old',
      "aggravate": '/english-aggravate',
      "aggravation": '/english-aggravation',
      "aggregate": '/english-aggregate',
      "aggression": '/english-aggression',
      "aggressive": '/english-aggressive',
      "aggressively": '/english-aggressively',
      "aggressiveness": '/english-aggressiveness',
      "aggressor": '/english-aggressor',
      "aggrieved": '/english-aggrieved',
      "aghast": '/english-aghast',
      "agile": '/english-agile',
      "agility": '/english-agility',
      "aging": '/english-aging',
      "agitate": '/english-agitate',
      "agitation": '/english-agitation',
      "agitator": '/english-agitator',
      "AGM": '/english-agm',
      "agnostic": '/english-agnostic',
      "agonized": '/english-agonized',
      "agonizing": '/english-agonizing',
      "agony": '/english-agony',
      "agony aunt": '/english-agony-aunt',
      "agoraphobia": '/english-agoraphobia',
      "agoraphobic": '/english-agoraphobic',
      "agrarian": '/english-agrarian',
      "agree": '/english-agree',
      "agreeable": '/english-agreeable',
      "agreeably": '/english-agreeably',
      "agreement": '/english-agreement',
      "agriculture": '/english-agriculture',
      "agricultural": '/english-agricultural',
      "agritourism": '/english-agritourism',
      "agrochemical": '/english-agrochemical',
      "agronomist": '/english-agronomist',
      "agronomy": '/english-agronomy',
      "aground": '/english-aground',
      "ahead": '/english-ahead',
      "ahead of": '/english-ahead-of',
      "AI": '/english-ai',
      "aid": '/english-aid',
      "aide": '/english-aide',
      "AIDS": '/english-aids',
      "ailing": '/english-ailing',
      "ailment": '/english-ailment',
      "aim": '/english-aim',
      "aimless": '/english-aimless',
      "aimlessly": '/english-aimlessly',
      "ain't": '/english-aint',
      "air": '/english-air',
      "airbag": '/english-airbag',
      "airborne": '/english-airborne',
      "air conditioner": '/english-air-conditioner',
      "air-conditioned": '/english-air-conditioned',
      "aircraft": '/english-aircraft',
      "aircraft carrier": '/english-aircraft-carrier',
      "airfield": '/english-airfield',
      "air force": '/english-air-force',
      "air hostess": '/english-air-hostess',
      "airlift": '/english-airlift',
      "airline": '/english-airline',
      "airliner": '/english-airliner',
      "airmail": '/english-airmail',
      "air-marshal": '/english-air-marshal',
      "airplane": '/english-airplane',
      "airport": '/english-airport',
      "air raid": '/english-air-raid',
      "airship": '/english-airship',
      "airspace": '/english-airspace',
      "airstrip": '/english-airstrip',
      "air terminal": '/english-air-terminal',
      "airtight": '/english-airtight',
      "air-to-air": '/english-air-to-air',
      "air traffic controller": '/english-air-traffic-controller',
      "airway": '/english-airway',
      "airworthy": '/english-airworthy',
      "airing": '/english-airing',
      "airing cupboard": '/english-airing-cupboard',
      "airless": '/english-airless',
      "airily": '/english-airily',
      "aisle": '/english-aisle',
      "ajar": '/english-ajar',
      "akin": '/english-akin',
      "à la carte": '/english-a-la-carte',
      "alacrity": '/english-alacrity',
      "alarm": '/english-alarm',
      "alarm clock": '/english-alarm-clock',
      "alarming": '/english-alarming',
      "alas": '/english-alas',
      "albatross": '/english-albatross',
      "albeit": '/english-albeit',
      "albino": '/english-albino',
      "album": '/english-album',
      "alcohol": '/english-alcohol',
      "alcoholic": '/english-alcoholic',
      "alcoholism": '/english-alcoholism',
      "alcove": '/english-alcove',
      "ale": '/english-ale',
      "alert": '/english-alert',
      "algae": '/english-algae',
      "algebra": '/english-algebra',
      "algorithm": '/english-algorithm',
      "alias": '/english-alias',
      "alibi": '/english-alibi',
      "alien": '/english-alien',
      "alienate": '/english-alienate',
      "alienation": '/english-alienation',
      "alight": '/english-alight',
      "align": '/english-align',
      "alignment": '/english-alignment',
      "alike": '/english-alike',
      "alimentary canal": '/english-alimentary-canal',
      "alimony": '/english-alimony',
      "alive": '/english-alive',
      "alkali": '/english-alkali',
      "all": '/english-all',
      "all-clear": '/english-all-clear',
      "all-in": '/english-all-in',
      "all-out": '/english-all-out',
      "all-rounder": '/english-all-rounder',
      "Allah": '/english-allah',
      "allay": '/english-allay',
      "allegation": '/english-allegation',
      "allege": '/english-allege',
      "alleged": '/english-alleged',
      "allegedly": '/english-allegedly',
      "allegiance": '/english-allegiance',
      "allegory": '/english-allegory',
      "allegorical": '/english-allegorical',
      "alleluia": '/english-alleluia',
      "allergy": '/english-allergy',
      "allergic": '/english-allergic',
      "alleviate": '/english-alleviate',
      "alleviation": '/english-alleviation',
      "alley": '/english-alley',
      "alliance": '/english-alliance',
      "allied": '/english-allied',
      "alligator": '/english-alligator',
      "alliteration": '/english-alliteration',
      "allocate": '/english-allocate',
      "allocation": '/english-allocation',
      "allot": '/english-allot',
      "allotment": '/english-allotment',
      "allow": '/english-allow',
      "allowable": '/english-allowable',
      "allowance": '/english-allowance',
      "alloy": '/english-alloy',
      "all right": '/english-all-right',
      "allude to": '/english-allude-to',
      "allusion": '/english-allusion',
      "alluring": '/english-alluring',
      "ally": '/english-ally',
      "almanac": '/english-almanac',
      "almighty": '/english-almighty',
      "almond": '/english-almond',
      "almost": '/english-almost',
      "alms": '/english-alms',
      "aloft": '/english-aloft',
      "alone": '/english-alone',
      "along": '/english-along',
      "alongside": '/english-alongside',
      "aloof": '/english-aloof',
      "aloofness": '/english-aloofness',
      "aloud": '/english-aloud',
      "alphabet": '/english-alphabet',
      "alphabetical": '/english-alphabetical',
      "alphabetically": '/english-alphabetically',
      "already": '/english-already',
      "alright": '/english-alright',
      "Alsatian": '/english-alsatian',
      "also": '/english-also',
      "altar": '/english-altar',
      "alteration": '/english-alteration',
      "alternate": '/english-alternate',
      "alternately": '/english-alternately',
      "alternating current": '/english-alternating-current',
      "alternation": '/english-alternation',
      "alternative": '/english-alternative',
      "alternatively": '/english-alternatively',
      "alternator": '/english-alternator',
      "although": '/english-although',
      "altitude": '/english-altitude',
      "alto": '/english-alto',
      "contralto": '/english-contralto',
      "altogether": '/english-altogether',
      "altruism": '/english-altruism',
      "altruistic": '/english-altruistic',
      "aluminium": '/english-aluminium',
      "always": '/english-always',
      "Alzheimer's disease": '/english-alzheimers-disease',
      "am": '/english-english-am',
      "a.m.": '/english-english-a-m',
      "amalgamate": '/english-amalgamate',
      "amalgamation": '/english-amalgamation',
      "amass": '/english-amass',
      "amateur": '/english-amateur',
      "amateurish": '/english-amateurish',
      "amaze": '/english-amaze',
      "amazement": '/english-amazement',
      "amazing": '/english-amazing',
      "ambassador": '/english-ambassador',
      "amber": '/english-amber',
      "ambidextrous": '/english-ambidextrous',
      "ambiguous": '/english-ambiguous',
      "ambiguity": '/english-ambiguity',
      "ambition": '/english-ambition',
      "ambitious": '/english-ambitious',
      "ambivalent": '/english-ambivalent',
      "ambivalence": '/english-ambivalence',
      "amble": '/english-amble',
      "ambulance": '/english-ambulance',
      "ambush": '/english-ambush',
      "ameba": '/english-ameba',
      "amen": '/english-amen',
      "amenable": '/english-amenable',
      "amend": '/english-amend',
      "amendment": '/english-amendment',
      "make amends": '/english-make-amends',
      "amenity": '/english-amenity',
      "American": '/english-american',
      "come of age": '/english-come-of-age',
      "far afield": '/english-far-afield',
      "from afar": '/english-from-afar',
      "under age": '/english-under-age',
      "American football": '/english-american-football',
      "amethyst": '/english-amethyst',
      "amiable": '/english-amiable',
      "amiably": '/english-amiably',
      "amicable": '/english-amicable',
      "amicably": '/english-amicably',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
      // "DOPSUM": '/english-DOPSUM',
    };

    final routeName = screenRoutes[word];

    if (routeName != null) {
      Routemaster.of(context).push(routeName);
    }
  }
}
