// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUTDS4ZAjQbw4EQCBwo0SdTMXKH68OtE',
    appId: '1:676072533272:web:bf00b6ee4874660c62c26d',
    messagingSenderId: '676072533272',
    projectId: 'zeetionary-9915d',
    authDomain: 'zeetionary-9915d.firebaseapp.com',
    storageBucket: 'zeetionary-9915d.appspot.com',
    measurementId: 'G-T07G8DY4D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKlYJWWIWefR6Si80q5Ib_oPD8j45qYqg',
    appId: '1:676072533272:android:959e8617f92794d862c26d',
    messagingSenderId: '676072533272',
    projectId: 'zeetionary-9915d',
    storageBucket: 'zeetionary-9915d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJjtU4DoZyqGuiIdYgJp_P_dVuaUgyQk',
    appId: '1:676072533272:ios:a397d761a433629462c26d',
    messagingSenderId: '676072533272',
    projectId: 'zeetionary-9915d',
    storageBucket: 'zeetionary-9915d.appspot.com',
    iosBundleId: 'com.example.zeetionary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJjtU4DoZyqGuiIdYgJp_P_dVuaUgyQk',
    appId: '1:676072533272:ios:07b71b4cdd2b0a5e62c26d',
    messagingSenderId: '676072533272',
    projectId: 'zeetionary-9915d',
    storageBucket: 'zeetionary-9915d.appspot.com',
    iosBundleId: 'com.example.zeetionary.RunnerTests',
  );
}
